# Generated by Django 3.1.7 on 2021-05-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_competed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-timestamp']},
        ),
    ]
